# przyciski
BUTTON_SIZE = (83, 16)
BUTTON_FONT_SIZE = 8

# suwak
SLIDER_HEIGHT = 4
SLIDER_BUTTON_SIZE = (4, 22)
SLIDER_COLOR = (255, 255, 255)
SLIDER_BUTTON_COLOR = (255, 255, 255)
SLIDER_BUTTON_COLOR_TOUCHED = (152, 245, 242)
SLIDER_BUTTON_COLOR_ACTIVATED = (94, 94, 94)
SLIDER_BORDER_RADIUS = 3

# gra
GAME_OVER_POS = 55
GAME_OVER_START_POS = 180
CAMERA_SCROLL_SHIFT = 50
UNDER_SCREEN_TOLERANCE = 30

# program
DRAW_SCREEN_SIZE = (320, 180)

# schodki
SLABS_DISTANCE = 40
SLAB_BLOCK_WIDTH = 16
BIG_SLAB_DISTANCE = 50

# zegarek
CLOCK_SHAKE_INTENSITY = 2
CLOCK_WAVING_INTENSITY = 5
CLOCK_WAVING_DISTORTION = 1
CLOCK_WAVING_SPEED = 0.1
CLOCK_WAVING_DIRECTION_CHANGE_INTERLUDE = 10
CLOCK_WAVING_SMOOTH = 15

# trzesienie ekranu przy spadnieciu
SCREEN_SHAKE_INTERLUDE = 30
SCREEN_SHAKE_INTESITY = 2
SCREEN_SHAKE_DURATION = 40
DARKEN_INTENSITY = 100

# animacje
CHARACTER_FRAME_SIZE = 24
JUMP_MIDDLE_ANIMATION_TIME = 1
ANIMATION_FRAME_NUMBERS = {
    "idle": 3,
    "walk": 4,
    "jump-start": 1,
    "jump-middle": 1,
    "jump-end": 1,
    "jump-up": 1,
    "rotate": 1
}

# particle
PARTICLE_SIZE = (1, 3)
PARTICLE_SPEED = 0.5
PARTICLE_OPACITY_SPEED = 5
PARTICLE_START_POINT_RANDOM = 5
PARTICLE_SPAWN_TIME = 2

# inne
WINDOW_DISTANCE = 300
PARALLAX_DEPTH = 2

# dzwiek
CHANNEL_QUANTITY = 9
START_VOLUME = 0.5

# napisy combo
COMBO_CAPTION_TIME = 300
COMBO_CAPTION_TYPES = {10: "great", 20: "nice", 30: "wow", 40: "super", 50: "amazing"}
COMBO_CAPTION_SMOOTH = 25
COMBO_CAPTION_POS = (160, 100)
COMBO_CAPTION_MARGIN = 100
COMBO_CAPTION_LEFT_SPEED_MULTIPLIER = 1.6
COMBO_CAPTION_WAVING_SPEED = 0.2
COMBO_CAPTION_WAVING_INTENSITY = 2
